### ISSUE TITLE
量化效果验证的一致性

### ISSUE THREAD

**Issue by NingSheng** [zhexinli/Q-ViT-DeiT#2]
请问量化后，分类准确率衰减与其它下游任务如目标检测、语义分割等，效果会基本一致吗？或者作者您对目前大多数的量化工作，只在分类上验证效果，有什么见解吗？

**Comment by zhexinli** [comment]
量化效果与任务、模型、数据分布都高度相关。同一个模型在分类任务上的表现不代表其作为 backbone 时在检测分割任务上的表现。总体上检测分割任务比分类任务更难量化。
学术界只在分类任务上刷点无可厚非，毕竟学术界关心的是一个方法的novelty，工业界才更关心才在具体任务上的指标。
