### ISSUE TITLE
Size of the model

### ISSUE THREAD

**Issue by sravanthOppo27** [zhexinli/Q-ViT-DeiT#4]
Does the size of the model reduces after this implementation . I can't see any reduction after applying this . The checkpoint size remains the same . Also inference time is not reduced and even it is worse than the float model .

Am I doing anything wrong ? or is the code provided here is wrong ?

Could anyone please confirm this ?

**Comment by zhexinli** [comment]
QAT(Quantization-aware Training)  is only an intermedia step of quantization. It must keep the latent weight (the float weight) for accuracy, so the model size remains the same. To achieve true model size compression and infer accelaration, you'll need hard-ware platform and inference framework such as GPU with TensorRT.

**Comment by sravanthOppo27** [comment]
I am using GPU's for training , But using gpu should reduce model size right ? .

**Comment by zhexinli** [comment]
Quantization is complicated in engineering. You need TensorRT to deploy QAT model on Nvidia-GPU. And for now TensorRT only support uniform int8 inference. See https://developer.nvidia.com/tensorrt-getting-started

**Comment by sravanthOppo27** [comment]
So , Let me get this straight . Model size won't change by this code . For getting the reduced inference time for quantized model we need to get the tensorRT framewok & tensorRT doesn't support mixed quantization. So we can't caluclate the inference of your proposed method as of now . We can only constrain it to reduced bitops . 

Correct me If I am wrong ?.

**Comment by zhexinli** [comment]
Yes of course, because this paper is an implementation for a conference paper for research purpose instead of a quantization toolkit. TensorRT do not support mixed-precision quantization but there are some NPUs that do support.

And by the way, model size can be reduced if you know how to use TensorRT. I assume you don't understand QAT's purpose. I suggest you read more papers.
